#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'HDMI-A-0 connected') ]]; then
  xrandr --output 'HDMI-A-0' --mode 1440x900 -r 74.98 --rotate normal &
  bspc monitor eDP -d 1 2 3 4 5 &
  bspc monitor HDMI-A-0 -d 6 7 8 9 10 &
else
  bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10 &
fi


bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Autostart
sh ~/.config/polybar/launch.sh &

  # Wallpaper
  feh --bg-scale ~/Imágenes/cyberpunk-city.jpg &

# Mouse
picom --experimental-backends &
xsetroot -cursor_name left_ptr &
